---
- name: enable postfix
  service: name=postfix state=started enabled=yes

- name: restart postfix
  service: name=postfix state=restarted enabled=yes

- name: enable dovecot
  service: name=dovecot state=started enabled=yes

- name: restart dovecot
  service: name=dovecot state=restarted enabled=yes

