---
- name: Install postfix
  yum: name=postfix state=present
  notify:
    - enable postfix
    - restart postfix

- name: Install dovecot
  yum: name=dovecot state=present
  notify:
    - enable dovecot
    - restart dovecot

- name: Install cyrus-sasl
  yum: name=cyrus-sasl state=present

- name: Install cyrus-sasl-lib
  yum: name=cyrus-sasl-lib state=present

- name: Install cyrus-sasl-plain
  yum: name=cyrus-sasl-plain state=present

- name: Install spammassassin
  yum: name=spamassassin state=present

- name: Install perl-Razor-Agent
  yum: name=perl-Razor-Agent state=present

- name: Install pypolicyd-spf
  yum: name=pypolicyd-spf state=present

- name: copy main.cf
  copy: src=etc/postfix/main.cf dest=/etc/postfix/main.cf

- name: copy master.cf
  copy: src=etc/postfix/master.cf dest=/etc/postfix/master.cf