---
- name: Install EPEL
  yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm state=present

- name: Install Remi
  yum: name=http://rpms.remirepo.net/enterprise/remi-release-7.rpm state=present

- name: install yum utils
  yum: name=yum-utils state=present

- name: copy remi.repo settings
  shell: yum-config-manager --enable remi-php70

#- name: yum update system
#  yum: name=* state=latest

- name: Install deltarpm
  yum: name=deltarpm state=present