---
- name: Install
  yum: name=fail2ban state=present
  notify:
    - enable fail2ban
    - restart fail2ban

- name: Install Gamin
  yum: name=gamin state=present

- name: copy fail2ban settings
  template:
    src=etc/fail2ban/jail.d/fail2ban.conf
    dest=/etc/fail2ban/jail.d/fail2ban.conf